# Westwing
version: '3.6'
services:
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    depends_on:
    - backend1
    - backend2
    networks:
      - default
  backend1:
    build: ./backend
    ports:
      - "5001:5000"
    networks:
      - default
  backend2:
    build: ./backend
    ports:
      - "5002:5000"
    networks:
      - default
  mysql:
    image: percona:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: westwing
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - default